#!/usr/bin/with-contenv bash

while [ ! -f /tmp/state/99-container-init ]
do
  sleep 1
done


if [ ! -f /tmp/state/09-nginx ]; then
	### Force Reset Permissions for Security
    	chown -R nginx /app/web
        mkdir -p /tmp/state/
		echo 'Initialization Complete' >/tmp/state/09-nginx
fi

echo ''
echo '** [openeats] Starting nginx'
source /app/api/.env
exec nginx
