#!/usr/bin/with-contenv bash

  ### Adjust NGINX Runtime Variables
  UPLOAD_MAX_SIZE=${UPLOAD_MAX_SIZE:="2G"}

  sed -i -e "s/<UPLOAD_MAX_SIZE>/$UPLOAD_MAX_SIZE/g" /etc/nginx/nginx.conf
  sed -i -e "s/<API_PORT>/$API_PORT/g" /etc/nginx/conf.d/default.conf

  mkdir -p /www/logs/nginx
  chown -R nginx /www/logs/nginx
  mkdir -p /tmp/nginx
  chown -R nginx /tmp/nginx

  mkdir -p /app/data/media
  mkdir -p /app/data/static
  
  chown -R nginx:www-data /app
  
  mkdir -p /tmp/state
  touch /tmp/state/09-init-nginx
